### ISSUE TITLE
Setup Kanban board

### ISSUE THREAD

**Issue by edenlisk** [AmanWorku/Space-Travelers-Hub#24]
In our team, we are 3 members.
1. @edenlisk 
2. @AmanWorku 
3. @Ofarouq310 
[Link to kanban project](https://github.com/AmanWorku/Space-Travelers-Hub/projects/1)

**Comment by Ghiftee** [comment]
## STATUS: CHANGES REQUIRED ♻️♻️
Hello team 👋🏽 

Good job working on the project so far! 
To highlight 👍🏽 
✔️ Points between group members are equal
✔️ Issue contains a link to your project

However, there are some issues that you need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

## Required Changes ♻️
- [ ] There should be 24 cards in total on your kanban board but you currently have 23. Kindly add the missing card.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- I suggest you include the names of every team member working on your project to the team members information above. This would make it more professional.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by TuyishimireEric** [comment]
# Status: APPROVED 🟢  
### Hi  @Team 👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job so implementing the project requirements! 🥇 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉 

## Highlights
✔️professional kanban👍 

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AmanWorku** [comment]
Thank you sir!
